export const DEFAULT_S3_SETTINGS: Record<string, string> = {
  'storage.s3Enabled': 'false',
  'storage.s3Endpoint': '',
  'storage.s3Port': '443',
  'storage.s3UseSSL': 'true',
  'storage.s3Region': '',
  'storage.s3Bucket': '',
  'storage.s3AccessKey': '',
  'storage.s3SecretKey': '',
}

export const DEFAULT_SETTINGS: Record<string, string> = {
  'app.name': 'ShareDrive',
  'app.baseUrl': 'http://localhost',
  'app.description': 'Fast, secure & beautiful file sharing',
  'app.maxFilesPerTransfer': '100',
  'storage.maxFileSizeBytes': '5368709120',
  'storage.maxTransferSizeBytes': '10737418240',
  'storage.userStorageQuotaBytes': '0',
  'storage.retentionDaysAnonymous': '7',
  'storage.retentionDaysRegistered': '30',
  ...DEFAULT_S3_SETTINGS,
  'email.enabled': 'false',
  'email.host': '',
  'email.port': '587',
  'email.secure': 'false',
  'email.user': '',
  'email.password': '',
  'email.from': 'noreply@sharedrive.local',
  'security.registrationEnabled': 'true',
  'security.requireEmailVerification': 'false',
  'security.virusScanEnabled': 'true',
  'appearance.primaryColor': '#6366f1',
  'appearance.logoUrl': '',
  'appearance.faviconUrl': '',
  'privacy.logRetentionDays': '30',
  'legal.privacyPolicy': '',
  'legal.imprint': '',
}
