Foreground yes
LogTime yes
LogClean no
DatabaseDirectory /data/clamav
User clamav
TCPSocket 3310
TCPAddr 127.0.0.1
LocalSocket /run/clamav/clamd.sock
FixStaleSocket yes
LocalSocketMode 600
PidFile /run/clamav/clamd.pid
StreamMaxLength 6144M
MaxFileSize 6144M
MaxScanSize 6144M
AlertExceedsMax yes
SelfCheck 600
ConcurrentDatabaseReload no
