[unix_http_server]
file=/run/sharedrive/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/sharedrive/supervisor.pid
childlogdir=/run/sharedrive

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/sharedrive/supervisor.sock

[program:postgres]
command=python3 /opt/sharedrive/aio/service.py postgres
priority=10
autorestart=true
startsecs=5
startretries=5
stopsignal=INT
stopwaitsecs=60
stopasgroup=false
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
command=python3 /opt/sharedrive/aio/service.py redis
priority=20
autorestart=true
startsecs=5
startretries=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:minio]
command=python3 /opt/sharedrive/aio/service.py minio
priority=20
autorestart=true
startsecs=5
startretries=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:clamav]
command=python3 /opt/sharedrive/aio/service.py clamav
priority=20
autorestart=true
startsecs=5
startretries=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:freshclam]
command=python3 /opt/sharedrive/aio/service.py freshclam
priority=30
autorestart=true
startsecs=5
startretries=5
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:app]
command=python3 /opt/sharedrive/aio/service.py app
priority=100
autorestart=true
startsecs=10
startretries=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
